name: Run tests on push
on: [push, pull_request]
push:
  paths:
    - "*.js"
pull_request:
  paths:
    - "*.js"

jobs:
  build:
    name: Lint and Test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@master
    - name: Set Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 10.x
    - name: Install dependencies
      run: npm ci
    - name: Lint
      needs: Install dependencies
      run: npm run lint
    - name: Test
      needs: Install dependencies
      run: npm test
