on: pull_request
name: Notify of New PRs
jobs:
  telegramNotify:
    name: Telegram Notify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Telegram Notify
      uses: appleboy/telegram-action@0.0.3
      env:
        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      with:
        args: A PR has been updated in `puregarlic/socks`
